name: iot_tar_project
description: Trabalho Pratico de TAR - Aplicacao movel

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  mqtt_client: 5.3.0
  flushbar: ^1.8.2
  flutter_launcher_icons: ^0.7.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  image_path: "icon.jpg"
  android: true

flutter:
  uses-material-design: true